1 items
nbschool/ecommerce_web pull request #2
Opened 2017-05-03 18:29 UTC by toysroom

il package https://github.com/philcockfield/storybook-host che mi avevi suggerito non mi sembrava molto adatto al test dei componenti a risoluzioni diverse. Mi sembra più adatto https://github.com/PeterPanen/storybook-addon-scissors che aggiunge nella console dello storybook una tendina per poter switchare device.

Per il resto, ho implementato il componente Item e ItemList come da specifica (spero).
Ho rimosso i componenti About e Home, ma ho lasciato i rispettivi container e moduli perché mi potrebbero essere utili nei prossimi issue come esempi.

2017-05-04 11:18 UTC, gvaldambrini requested changes

2017-05-04 11:18 UTC, gvaldambrini commented on src/components/Item/Item.js
> +  return (
Puoi rimuovere la graffa e il return visto che l'unica cosa che fai è un return

2017-05-04 11:18 UTC, gvaldambrini commented on src/components/Item/Item.sass
> +      flex-grow: 1
poiché usiamo sass, occhio all'indentazione (flex-grow è a sinistra di flex-basis e gli altri elementi di `card`)

2017-05-04 11:18 UTC, gvaldambrini commented on src/components/ItemList/ItemList.js
> +    else{
mi ero dimenticato di aggiungere una regola di eslint per questo, lo faccio così ti darà errore :D

2017-05-04 11:18 UTC, gvaldambrini commented on stories/index.js
> +    return (<Item
non riesco a trovare una regola per farti andare a capo dopo la parentesi, ma please fallo

2017-05-04 11:19 UTC, gvaldambrini commented
Va benissimo aver usato scissors, che mi sembra un'ottima aggiunta che non conoscevo. E' necessario però che i contenitori siano rimossi perlomeno dall'App, altrimenti il server dà errore perché hai rimosso i componenti ma non i contenitori

2017-05-04 19:15 UTC, toysroom commented on src/components/Item/Item.js
> +  return (
ok, fatto

2017-05-04 19:16 UTC, toysroom commented on src/components/Item/Item.sass
> +      flex-grow: 1
giusto, corretto

2017-05-04 19:19 UTC, toysroom commented on stories/index.js
> +    return (<Item
ok

2017-05-04 19:20 UTC, toysroom commented on src/components/ItemList/ItemList.js
> +    else{
non ho capito a cosa ti riferisci

2017-05-04 19:27 UTC, toysroom commented
ho corretto 3 delle 4 cose segnalate perché una non l'ho capita. 
non ho neanche capito quella cosa dell'upstream. se volessi fare pull del master che devo scrivere?

git pull origin master ?

2017-05-04 19:36 UTC, gvaldambrini commented on src/components/ItemList/ItemList.js
> +    else{
tipicamente gli statement sono separati da un spazio prima che ci sia una parentesi. Quindi l'else si scriverebbe come:
```
else {
```

2017-05-04 19:45 UTC, gvaldambrini commented
Relativamente alla storia dell'upstream, ci riprovo 😄 
git (attenzione, non github, sono due cose diverse) prevede che per un repository tu possa avere più remote. Quando fai il clone di un repository, per esempio da github, ti viene creato in automatico un remote chiamato `origin`che punta al tuo repository su github. Questo non ti vieta di aggiungere altri remote. Puoi vedere la lista dei remote che hai configurato per un certo repository con `git remote`. Con lo stesso `git remote` puoi aggiungere un altro remote. Sulla API abbiamo aggiunto un remote che per convenzione è stato chiamato `upstream` e che punta al repository principale dal quale sono nati i vari fork. Quindi, se vuoi ricreare la stessa situazione sulla parte web, è necessario aggiungere come remote il repository principale con:
```
git remote add upstream <indirizzo>
```
in questo modo sarai in grado di fare il pull dal repository principale quando le pull request saranno mergiate (ma non fare il push perché non hai su quel repository i permessi di scrittura e puoi unicamente creare pull request). Chiaramente `origin` rimane il tuo fork, e su quello puoi fare che ti pare. 
Mi sono spiegato meglio ora? 😄

2017-05-10 09:01 UTC, gvaldambrini requested changes

2017-05-10 09:01 UTC, gvaldambrini commented on src/components/App/App.js
> +      <li><Link to="/">ItemList</Link></li>
Ma questo link a che serve? Mi viene da dire che puoi scegliere due strade:
 * rimuovi il link e quindi "/" mostra direttamente ItemList
 * modifichi il link perché sia un "/items" modifichi le routes definite in index.js perché mostri ItemList quando il path è "/items"

2017-05-10 09:01 UTC, gvaldambrini commented on src/components/Item/Item.js
> +  return (
anche questo non l'hai davvero fatto poi 🎱

2017-05-10 09:01 UTC, gvaldambrini commented on src/components/Item/Item.js
> +          <div className="description">{item.description}</div>
ma perché non passare direttamente le proprietà richieste piuttosto che l'oggetto `item`? Chiaramente a quel punto dove usi il componente Item dovresti scrivere:
```
<Item {...item} />
```

2017-05-10 11:12 UTC, gvaldambrini requested changes

2017-05-10 11:12 UTC, gvaldambrini commented on src/components/Item/Item.sass
> +    -webkit-box-orient: vertical
ma serve davvero questa roba? create-react-app è [configurato](https://github.com/facebookincubator/create-react-app#whats-inside) per usare [autoprefixer](https://github.com/postcss/autoprefixer), quindi ho il sospetto che tu non ne abbia bisogno, sbaglio?

2017-05-10 11:12 UTC, gvaldambrini commented on src/components/Item/Item.js
> +        <img src="http://placehold.it/150x250" alt="" />
questo placeholder scarichiamolo e usiamo da locale, in modo che la nostra applicazione non dipenda da un'url esterna solo per un placeholder. 
Basta che metti l'immagine in una directory locale (in questo caso la puoi mettere dentro al componente Item) e poi la carichi nel bundle stesso tramite webpack, come descritto qua:
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-images-fonts-and-files

2017-05-11 10:24 UTC, merged