Added SidebarMenu, PersonalAreaPersonalData, PersonalAreaAddressData …
nbschool/ecommerce_web pull request #33
Opened 2017-05-31 16:02 UTC by toysroom

…and PersonalArea component with relative styles, languages, storybook and snapshot

2017-06-01 11:16 UTC, GendoIkari commented on src/components/App/App.sass
> +
Questi vanno in palette.sass, ma cerchiamo di armonizzare lo stile. Quindi magari usiamo il primary color già usato, e gli altri il più possibile. Evitiamo di avere milioni di colori diversi.
Invece di aggiungere colori possiamo giocare con le shadow, con le forme, etc...

2017-06-01 11:16 UTC, GendoIkari commented on src/components/PersonalArea/PersonalArea.js
> +      <div className="PersonalArea">
Usiamo tag semantici!!!

2017-06-01 11:16 UTC, GendoIkari commented on src/components/PersonalArea/PersonalArea.js
> +        <h3>{t('personalArea:title')}</h3>
H1

2017-06-01 11:16 UTC, GendoIkari commented on src/components/PersonalArea/PersonalArea.js
> +  t: PropTypes.func.isRequired,
Questo t in altri componenti lo abbiamo messo in fondo, giusto? E' una cazzata, ma cerchiamo di mantenere uno stile coerente. Le props non nostre, come t, le mettiamo in fondo, dopo le nostre.

2017-06-01 11:16 UTC, GendoIkari commented on src/components/PersonalArea/PersonalArea.sass
> +.PersonalArea
Ma questo è il lint che vi dice di fare così? Io metterei un paio di spazi dopo gli import. O almeno uno.

2017-06-01 11:16 UTC, GendoIkari commented on src/components/PersonalArea/PersonalArea.sass
> +          flex-direction: column
Per ora va bene così, poi queste le mettiamo in breakpoints.sass.

2017-06-06 10:07 UTC, gvaldambrini requested changes

2017-06-06 10:07 UTC, gvaldambrini commented on src/components/App/App.sass
> +// $color-link-sidebar-active: #fff
Gendo direbbe "roba commentata committataaaaaa"

2017-06-06 10:07 UTC, gvaldambrini commented on src/components/PersonalArea/PersonalArea.js
> +      saveData={this.props.saveData} />;
oddio, questa indentazione mi turba. All'inzio pensavo che ci fosse un errore poiché non hai messo le graffe nell'if e quanto viene dopo è indentato allo stesso livello. Aggiungi un livello di indentazione per le props di area?

2017-06-06 10:07 UTC, gvaldambrini commented on src/components/PersonalArea/PersonalArea.js
> +    let area = '';
puoi scrivere:
```
let area;
```
anche `undefined` o `null` renderizzano niente per un blocco di jsx, quindi non c'è bisogno che lo inizializzi alla stringa vuota.

2017-06-06 10:07 UTC, gvaldambrini commented on src/components/PersonalArea/PersonalArea.js
> +              setActiveArea={(area) => this.setActiveArea(area)} />
come piccola ottimizzazione, qua stai creando una arrow function ogni volta che viene fatta la render, puoi evitarlo se fai il bind nel costruttore:
```
this.setActiveArea = this.setActiveArea.bind(this);
```

2017-06-06 10:07 UTC, gvaldambrini commented on src/components/PersonalAreaPersonalData/PersonalAreaPersonalData.js
> +        <form className="form" onSubmit={(event) => this.submitData(event)}>
stessa storia di sopra, visto che ormai siamo grandi usiamo le bind

2017-06-06 10:07 UTC, gvaldambrini commented on src/components/SidebarMenu/SidebarMenu.js
> +      active: props.active ? props.active : 'personalarea'
ma non potevi mettere un default per questa props?

2017-06-06 10:07 UTC, gvaldambrini commented on src/components/SidebarMenu/SidebarMenu.js
> +    this.props.setActiveArea(area.name);
Ma che bisogno c'è dello stato locale? Non si può usare direttamente la props active e il metodo setActiveArea?

2017-06-07 09:36 UTC, merged