#3 added_fetch_picture_to_every_Item
nbschool/ecommerce_web pull request #6
Opened 2017-05-12 10:06 UTC by ceskomira90

2017-05-12 10:12 UTC, GendoIkari commented on src/modules/items.js
> +      items: addPictureToItem(action.payload, state),
Ecco ripensandoci, cio' che possiamo fare qui e' passare state.items e far ritornare la lista di items patchata.

2017-05-12 10:12 UTC, GendoIkari commented on src/modules/items.js
> +  return state.items = [...state.items];
Ecco qui sarebbe un
```
return [...state.items];
```

2017-05-22 08:20 UTC, gvaldambrini requested changes

2017-05-22 08:20 UTC, gvaldambrini commented on src/components/Item/Item.js
> +        <img src={pictureUrl} alt="" />
perché hai tolto l'alt???

2017-05-22 08:20 UTC, gvaldambrini commented on src/modules/items.js
> +        dispatch(fetchPictureSuccess(picture));})
le parentesi graffe non servono visto che hai un'unica istruzione all'interno della arrow function.

2017-05-22 08:20 UTC, gvaldambrini commented on src/modules/items.js
> +function addPictureToItem(picture, items) {
aggiungiamo un po' di documentazione, in particolare per gli argomenti e il valore di ritorno

2017-05-22 08:20 UTC, gvaldambrini commented on src/modules/items.js
> +          item.pictureUrl = 'http://placehold.it/150x250';
Abbiamo deciso di non usare immagini prese da rete se non veramente necessarie. Qua potremmo non impostare `pictureUrl` o impostarlo a `null` e poi decidere a livello del componente Item se usare la url o il placeholder

2017-05-22 08:20 UTC, gvaldambrini commented on src/modules/items.js
> +      loaded: true,
direi che nel modulo `items` il `loaded` si possa riferire al fatto che gli items siano caricati o meno. Quindi direi di rimuovere l'impostazione del `loaded` da qua (più che altro per ragioni di coerenza, quando si arriva qua `loaded` sarà sicuramente true).

2017-05-22 08:20 UTC, gvaldambrini commented on src/components/Item/Item.js
> +
Come detto sotto, il placehold ci piace che sia importato da filesystem e poi usato se necessario.

2017-05-22 08:23 UTC, ceskomira90 commented on src/components/Item/Item.js
> +        <img src={pictureUrl} alt="" />
rebase scorretto. Modifico

2017-05-22 08:25 UTC, ceskomira90 commented on src/modules/items.js
> +      loaded: true,
vero. correggo

2017-05-22 10:10 UTC, gvaldambrini requested changes

2017-05-22 10:10 UTC, gvaldambrini commented on stories/index.js
> +      pictureUrl: 'placehold.png'
direi che potrebbe aver più senso passargli `null`

2017-05-22 10:20 UTC, merged